### ISSUE TITLE
Two fastapi http connections trying to use the same database connection?

### ISSUE THREAD

**Issue by ephes** [ephes/fastdeploy#31]
The result is seeing a 404 on a perfectly valid get deployment request. This is the server log:

```
/home/deploy/site/./deploy/service_layer/unit_of_work.py:82: SAWarning: The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7fcca7c53060>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
  self.steps = repository.SqlAlchemyStepRepository(self.session)
ERROR:deploy.service_layer.messagebus:Exception handling command name='Remove unit file for systemd service' deployment_id=250 state='success' started=datetime.datetime(2022, 7, 11, 16, 53, 46, 109512, tzinfo=datetime.timezone.utc) finished=datetime.datetime(2022, 7, 11, 16, 53, 46, 148180, tzinfo=datetime.timezone.utc) message=''
Traceback (most recent call last):
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 181, in bind_execute
  File "asyncpg/protocol/protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deploy/site/./deploy/views.py", line 89, in get_deployment_with_steps
    steps = await uow.steps.get_steps_by_deployment(deployment_id)
  File "/home/deploy/site/./deploy/adapters/repository.py", line 332, in get_steps_by_deployment
    result = await self.session.execute(stmt)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 212, in execute
    result = await greenlet_spawn(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1631, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
[SQL: SELECT step.id, step.name, step.started, step.finished, step.state, step.message, step.deployment_id
FROM step
WHERE step.deployment_id = %s]
[parameters: (250,)]
(Background on this error at: https://sqlalche.me/e/14/rvf5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 729, in rollback
    self.await_(self._transaction.rollback())
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/transaction.py", line 219, in rollback
    await self.__rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/transaction.py", line 198, in __rollback
    await self._connection.execute(query)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/asyncpg/connection.py", line 318, in execute
    return await self._protocol.query(query, timeout)
  File "asyncpg/protocol/protocol.pyx", line 323, in query
  File "asyncpg/protocol/protocol.pyx", line 707, in asyncpg.protocol.protocol.BaseProtocol._check_state
asyncpg.exceptions._base.InterfaceError: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 983, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 731, in rollback
    self._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.InterfaceError: <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/deploy/site/./deploy/service_layer/messagebus.py", line 55, in handle_command
    await handler(command)
  File "/home/deploy/site/./deploy/service_layer/handlers.py", line 111, in process_step
    deployment = await views.get_deployment_with_steps(command.deployment_id, uow)
  File "/home/deploy/site/./deploy/views.py", line 87, in get_deployment_with_steps
    async with uow:
  File "/home/deploy/site/./deploy/service_layer/unit_of_work.py", line 87, in __aexit__
    await super().__aexit__(*args)
  File "/home/deploy/site/./deploy/service_layer/unit_of_work.py", line 46, in __aexit__
    await self.rollback()
  File "/home/deploy/site/./deploy/service_layer/unit_of_work.py", line 96, in rollback
    await self.session.rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 576, in rollback
    return await greenlet_spawn(self.sync_session.rollback)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1399, in rollback
    self._transaction.rollback(_to_root=self.future)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 900, in rollback
    util.raise_(rollback_err[1], with_traceback=rollback_err[2])
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 865, in rollback
    t[1].rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in rollback
    self._do_rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2561, in _do_rollback
    self._close_impl(try_deactivate=True)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2544, in _close_impl
    self._connection_rollback_impl()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2536, in _connection_rollback_impl
    self.connection._rollback_impl()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 985, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 983, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 682, in do_rollback
    dbapi_connection.rollback()
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 731, in rollback
    self._handle_exception(error)
  File "/home/deploy/site/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.InterfaceError: (sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
(Background on this error at: https://sqlalche.me/e/14/rvf5)
(sqlalchemy.dialects.postgresql.asyncpg.InterfaceError) <class 'asyncpg.exceptions._base.InterfaceError'>: cannot perform operation: another operation is in progress
(Background on this error at: https://sqlalche.me/e/14/rvf5)
INFO:     136.243.145.93:0 - "POST /steps/ HTTP/1.1" 400 Bad Request
sys:1: SAWarning: transaction already deassociated from connection
'NoneType' object has no attribute '_new'
INFO:     78.49.93.16:0 - "GET /deployments/250 HTTP/1.1" 404 Not Found
ERROR:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:The garbage collector is trying to clean up connection <AdaptedConnection <asyncpg.connection.Connection object at 0x7fcca7b9fa00>>. This feature is unsupported on async dbapi, since no IO can be performed at this stage to reset the connection. Please close out all connections when they are no longer used, calling ``close()`` or using a context manager to manage their lifetime.
INFO:     78.49.93.16:0 - "GET /deployments/250 HTTP/1.1" 200 OK
```

**Comment by ephes** [comment]
Those ominous messages are somehow related:
```
Jun 16 14:53:04 staging deploy.py[3740663]: ERROR:sqlalchemy.pool.impl.AsyncAdaptedQueuePool:The garbage collector is trying to clean up connection <AdaptedC>
```

**Comment by ephes** [comment]
Ok, the root cause seems to be that providing SqlAlchemyUnitOfWork() as a default argument in the `bootstrap` function call causes it to be initialized at application start. And since `self.connection` / `self.session` is now global, all requests are sharing the same connection. Duh.
